import type { ClinicalSnapshot, EpisodeRecord, PatientRecord, TaskRecord } from "../domain/types";
import {
  careSettingLabel,
  displayMrn,
  normalizeText,
  pathwayLabel,
  priorityLabel,
  taskIsDueToday,
  taskIsOpen,
  taskIsOverdue,
  todayIso
} from "../domain/schema";

/**
 * Builds an end-of-day ward handover note as Markdown.
 *
 * The note DOES contain identifiers — that is its purpose — and it is written
 * only inside the configured clinical folder, exactly like every other
 * record. It replaces the manual re-typing a handover otherwise requires.
 */
export function buildHandoverNote(snapshot: ClinicalSnapshot, today = todayIso()): string {
  const patientById = new Map(snapshot.patients.map((patient) => [patient.id, patient] as const));
  const label = (patient: PatientRecord | undefined): string =>
    patient
      ? `MRN ${displayMrn(patient.mrn)} · ${patient.patient_name || "Name not recorded"}`
      : "Patient identity missing";

  const activeEpisodes = snapshot.episodes.filter(
    (episode) => !["archived", "cancelled", "entered-in-error"].includes(episode.status)
  );
  const priorityRank: Record<string, string> = { emergency: "0", urgent: "1", routine: "2" };
  const episodeLine = (episode: EpisodeRecord): string => {
    const patient = patientById.get(episode.patient_id);
    const next = normalizeText(episode.next_action)
      ? `next: ${episode.next_action}${episode.due_date ? ` (due ${episode.due_date})` : ""}`
      : "no outstanding action";
    return `- **${label(patient)}** — ${episode.case || "Case not recorded"} · ${pathwayLabel(episode.pathway)} · ${priorityLabel(episode.priority)} · ${next}`;
  };
  const bySortKey = (a: EpisodeRecord, b: EpisodeRecord): number =>
    `${priorityRank[a.priority] ?? "3"}|${a.due_date || "9999"}`.localeCompare(
      `${priorityRank[b.priority] ?? "3"}|${b.due_date || "9999"}`
    );

  const inpatients = activeEpisodes
    .filter((episode) => episode.care_setting === "inpatient")
    .sort(bySortKey);

  const openTasks = snapshot.tasks.filter(taskIsOpen);
  const urgentToday = openTasks
    .filter((task) => taskIsOverdue(task, today) || taskIsDueToday(task, today))
    .sort((a, b) => `${a.due_date || "9999"}`.localeCompare(`${b.due_date || "9999"}`));
  const taskLine = (task: TaskRecord): string => {
    const patient = patientById.get(task.patient_id);
    const state = taskIsOverdue(task, today) ? `overdue (${task.due_date})` : "due today";
    return `- ${task.task || "Task not recorded"} — ${label(patient)} · ${state}`;
  };

  const lines: string[] = [
    `# Ward handover — ${today}`,
    "",
    "> Generated by Clinical Workspace from the records on this device.",
    "> Verify against the ward list before relying on it; delete after use.",
    "",
    `## Inpatients (${inpatients.length})`,
    ""
  ];
  lines.push(
    ...(inpatients.length ? inpatients.map(episodeLine) : ["- No active inpatient episodes."])
  );
  lines.push("", `## Overdue and due today (${urgentToday.length})`, "");
  lines.push(
    ...(urgentToday.length ? urgentToday.map(taskLine) : ["- Nothing overdue or due today."])
  );
  const outpatientCount = activeEpisodes.length - inpatients.length;
  lines.push(
    "",
    `## Counts`,
    "",
    `- Active episodes: ${activeEpisodes.length} (${inpatients.length} ${careSettingLabel("inpatient").toLowerCase()}, ${outpatientCount} ${careSettingLabel("outpatient").toLowerCase()})`,
    `- Open tasks: ${openTasks.length}`,
    ""
  );
  return lines.join("\n");
}
