import type { ClinicalSnapshot, EpisodeRecord, PatientRecord, TaskRecord } from "../domain/types";
import {
  careSettingLabel,
  displayMrn,
  normalizeIsoDate,
  normalizeText,
  pathwayLabel,
  priorityLabel,
  taskIsDueToday,
  taskIsOpen,
  taskIsOverdue,
  taskIsUndated,
  taskIsUpcoming,
  todayIso
} from "../domain/schema";
import { priorityRank } from "../domain/transitions";
import { escapeMarkdownInline, survivingPatientLookup } from "./patient-list";

/**
 * Priority-first order for a worklist read from the top: emergency, then
 * urgent, then routine; within a priority the soonest due first and undated
 * last; then the record id, so every device lists the same tasks identically.
 */
export function compareTasksByPriority(a: TaskRecord, b: TaskRecord): number {
  return (
    priorityRank(b.priority) - priorityRank(a.priority) ||
    (normalizeIsoDate(a.due_date) || "9999").localeCompare(normalizeIsoDate(b.due_date) || "9999") ||
    a.id.localeCompare(b.id)
  );
}

/**
 * Builds an end-of-day ward handover note as Markdown.
 *
 * The note DOES contain identifiers — that is its purpose — and it is written
 * only inside the configured clinical folder, exactly like every other
 * record. It replaces the manual re-typing a handover otherwise requires.
 */
export function buildHandoverNote(snapshot: ClinicalSnapshot, today = todayIso()): string {
  // Work still filed under a merged-away patient is handed over under the
  // surviving patient, and clinical free text is escaped so a stray %%, #, or
  // [[ cannot hide the rest of the note or turn into a tag or link.
  const patientOf = survivingPatientLookup(snapshot.patients);
  const episodeById = new Map(snapshot.episodes.map((episode) => [episode.id, episode] as const));
  const text = (value: string | undefined, fallback: string): string =>
    normalizeText(value) ? escapeMarkdownInline(value ?? "") : fallback;
  const label = (patient: PatientRecord | undefined): string =>
    patient
      ? `MRN ${escapeMarkdownInline(displayMrn(patient.mrn))} · ${text(patient.patient_name, "Name not recorded")}`
      : "Patient identity missing";

  const activeEpisodes = snapshot.episodes.filter(
    (episode) => !["archived", "cancelled", "entered-in-error"].includes(episode.status)
  );
  const priorityRankKey: Record<string, string> = { emergency: "0", urgent: "1", routine: "2" };
  const episodeLine = (episode: EpisodeRecord): string => {
    const patient = patientOf(episode.patient_id);
    const next = normalizeText(episode.next_action)
      ? `next: ${escapeMarkdownInline(episode.next_action)}${episode.due_date ? ` (due ${escapeMarkdownInline(episode.due_date)})` : ""}`
      : "no outstanding action";
    return `- **${label(patient)}** — ${text(episode.case, "Case not recorded")} · ${pathwayLabel(episode.pathway)} · ${escapeMarkdownInline(priorityLabel(episode.priority))} · ${next}`;
  };
  const bySortKey = (a: EpisodeRecord, b: EpisodeRecord): number =>
    `${priorityRankKey[a.priority] ?? "3"}|${a.due_date || "9999"}`.localeCompare(
      `${priorityRankKey[b.priority] ?? "3"}|${b.due_date || "9999"}`
    );

  const inpatients = activeEpisodes
    .filter((episode) => episode.care_setting === "inpatient")
    .sort(bySortKey);

  // The covering team needs what is late, what is due, what starts first
  // thing tomorrow, and the open work nobody dated (including a date that no
  // longer parses) — each ranked by priority so an emergency is read first.
  const openTasks = snapshot.tasks.filter(taskIsOpen);
  const urgentToday = openTasks
    .filter((task) => taskIsOverdue(task, today) || taskIsDueToday(task, today))
    .sort(compareTasksByPriority);
  const dueTomorrow = openTasks
    .filter((task) => taskIsUpcoming(task, 1, today))
    .sort(compareTasksByPriority);
  const undated = openTasks.filter(taskIsUndated).sort(compareTasksByPriority);
  const taskLine = (task: TaskRecord): string => {
    const patient = patientOf(task.patient_id);
    const caseName = text(episodeById.get(task.episode_id)?.case, "Case not recorded");
    const due = normalizeIsoDate(task.due_date);
    const state = !due
      ? normalizeText(task.due_date)
        ? "due date unreadable"
        : "no date"
      : taskIsOverdue(task, today)
        ? `overdue (${due})`
        : due === today
          ? "due today"
          : `due ${due}`;
    return `- ${text(task.task, "Task not recorded")} — ${label(patient)} · ${caseName} · ${escapeMarkdownInline(priorityLabel(task.priority))} · ${state}`;
  };
  const section = (heading: string, tasks: TaskRecord[], empty: string): string[] => [
    "",
    `## ${heading} (${tasks.length})`,
    "",
    ...(tasks.length ? tasks.map(taskLine) : [`- ${empty}`])
  ];

  const lines: string[] = [
    `# Ward handover — ${today}`,
    "",
    "> Generated by Clinical Workspace from the records on this device.",
    "> Verify against the ward list before relying on it; delete after use.",
    "",
    `## Inpatients (${inpatients.length})`,
    ""
  ];
  lines.push(
    ...(inpatients.length ? inpatients.map(episodeLine) : ["- No active inpatient episodes."])
  );
  lines.push(...section("Overdue and due today", urgentToday, "Nothing overdue or due today."));
  lines.push(...section("Due tomorrow", dueTomorrow, "Nothing due tomorrow."));
  lines.push(...section("No date set", undated, "No open task without a date."));
  const outpatientCount = activeEpisodes.length - inpatients.length;
  lines.push(
    "",
    `## Counts`,
    "",
    `- Active episodes: ${activeEpisodes.length} (${inpatients.length} ${careSettingLabel("inpatient").toLowerCase()}, ${outpatientCount} ${careSettingLabel("outpatient").toLowerCase()})`,
    `- Open tasks: ${openTasks.length}`,
    ""
  );
  return lines.join("\n");
}
